### ISSUE TITLE
Utworzenie modelu bazy danych

### ISSUE THREAD

**Issue by DatabaseDropper** [DatabaseDropper/CloudDrive#10]
Model bazy danych powinien umożliwiać dane funkcjonalności:

User:
* Zalogowanie
* Wysyłkę e-maili
* Posiadanie swojego własnego dysku (każdy user ma swój dysk, nie ma konta bez dysku)

Disk:
* Zarządza miejscem na dysku (dostępne/zajęte)
* Posiada pod sobą folder lub foldery

Folder:
* Przechowywanie plików 
* Bycie udostępnionym dla 0 lub większej liczby innych użytkowników oraz zasady typu może usuwać pliki, może dodawać, może pobierać.
* Struktura drzewiasta. Folder może mieć pod sobą 0 lub wiele innych folderów. 

File:
* Informacje "fizyczne" nt. pliku - rozmiar, nazwa od usera, nazwa na dysku (prawdziwym)
* Dla kogo i na jakich zasadach (może pobrać, może usunąć) jest udostępniony

**Comment by hutyraprzemyslaw** [comment]
zrobione
